// <auto-generated />
// Run: scripts\bake-core-patch-hashes.ps1
#nullable enable
namespace NOLoader.Core.Patching
{
    public static partial class CoreBootstrapPatchHashes
    {
        /// <summary>Game root used when hashes were last baked.</summary>
        public const string BakedFromGameRoot = @"C:\\Program Files (x86)\\Steam\\steamapps\\common\\Nuclear Option";

        public static string? TryGet(string modId)
        {
            switch (modId)
            {
                case "noloader.bootstrap": return "D9E1CB68399FBA10";
                case "noloader.registry": return "E039721C070EB05F";
                case "noloader.physics": return "47A8A5BEE465F9DB";
                case "noloader.gatel4": return "FC4B1C7759298AD7";
                case "noloader.gatel4.scene": return "D5766C33F029604F";
                default: return null;
            }
        }
    }
}
