using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using NOLoader.Core.Patching;
using NOLoader.Patcher;

namespace NOLoader.PatchTool
{
    internal static class CorePatchHashBaker
    {
        private static readonly (string Module, Func<string, List<PatchEntry>> PlanFactory)[] Modules =
        {
            ("Assembly-CSharp.dll", CoreBootstrapPatches.CreateGameAssemblyPlan),
            ("UnityEngine.CoreModule.dll", CoreBootstrapPatches.CreateUnityCorePlan),
            ("UnityEngine.PhysicsModule.dll", CoreBootstrapPatches.CreateUnityPhysicsPlan)
        };

        public static int Bake(string gameRoot, string outputPath)
        {
            string loaderRoot = Path.Combine(gameRoot, "NOLoader");
            var hashes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            foreach ((string module, Func<string, List<PatchEntry>> planFactory) in Modules)
            {
                byte[]? snapshot = null;
                byte[]? bytes = AssemblyPatcher.LoadManagedModuleBytes(gameRoot, module, ref snapshot);
                if (bytes == null)
                {
                    Console.Error.WriteLine("Missing module: " + module);
                    return 1;
                }

                List<PatchEntry> plan = planFactory(loaderRoot);
                PatchSignatureResolver.PopulateMissingCoreHashes(bytes, gameRoot, plan);
                foreach (PatchEntry entry in plan)
                {
                    string? hash = entry.Descriptor.ExpectedSignatureHash;
                    if (string.IsNullOrEmpty(hash))
                    {
                        Console.Error.WriteLine(
                            "Failed to compute hash for " + entry.ModId + " (" + entry.Descriptor.Target + ")");
                        return 1;
                    }

                    hashes[entry.ModId] = hash!;
                }
            }

            string content = RenderSource(hashes, gameRoot);
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
            File.WriteAllText(outputPath, content, new UTF8Encoding(false));
            Console.WriteLine("Wrote " + hashes.Count + " baked hashes to " + outputPath);
            return 0;
        }

        private static string RenderSource(IReadOnlyDictionary<string, string> hashes, string gameRoot)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Run: scripts\\bake-core-patch-hashes.ps1");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace NOLoader.Core.Patching");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class CoreBootstrapPatchHashes");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>Game root used when hashes were last baked.</summary>");
            sb.AppendLine("        public const string BakedFromGameRoot = @\"" + gameRoot.Replace("\\", "\\\\") + "\";");
            sb.AppendLine();
            sb.AppendLine("        public static string? TryGet(string modId)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (modId)");
            sb.AppendLine("            {");

            foreach (KeyValuePair<string, string> pair in hashes)
            {
                sb.AppendLine("                case \"" + pair.Key + "\": return \"" + pair.Value + "\";");
            }

            sb.AppendLine("                default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
